### ISSUE TITLE
Exported files are not written

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tbleicher/su2rad#19]
```
What steps will reproduce the problem?
1. Start SU, draw a cube
2. Export without changing anything
3.

What is the expected output? What do you see instead?
Files describing geometry and materials .... Following folders are created but 
are empty, expect the skies folder where the sky can be found
ambfiles
images
logfiles
octrees
skies


What version of the product are you using? On what operating system?
daysim r03 on Windows 7

Please provide any additional information below.


```

Original issue reported on code.google.com by `chr.hv...@gmail.com` on 3 Mar 2012 at 9:52

**Comment by gwgill** [comment]
I have the same problem. System is 32 bit MSWindows, Sketchup 7.
(su2rad.rb doesn't have a LOGLEVEL value to change...)

Ruby console shows the following error after attempting an export:
[E] reference to deleted Layer
D:/bin/Sketchup7/Plugins/su2radlib/radiance_entities.rb:418:in `name'
D:/bin/Sketchup7/Plugins/su2radlib/radiance_entities.rb:418:in `getLayerName'
D:/bin/Sketchup7/Plugins/su2radlib/radiance_entities.rb:411:in `getEffectiveLayerName'
D:/bin/Sketchup7/Plugins/su2radlib/radiance_entities.rb:446:in `getPolygonText'
D:/bin/Sketchup7/Plugins/su2radlib/radiance_entities.rb:389:in `getText'
D:/bin/Sketchup7/Plugins/su2radlib/exportbase.rb:218:in `exportByGroup'
D:/bin/Sketchup7/Plugins/su2radlib/exportbase.rb:212:in `each_index'
D:/bin/Sketchup7/Plugins/su2radlib/exportbase.rb:212:in `exportByGroup'
D:/bin/Sketchup7/Plugins/su2radlib/radiancescene.rb:264:in `export'
D:/bin/Sketchup7/Plugins/su2radlib/radiancescene.rb:233:in `startExportWeb'
D:/bin/Sketchup7/Plugins/su2radlib/webdialog.rb:160:in `startExport'
D:/bin/Sketchup7/Plugins/su2radlib/webdialog.rb:74:in `show'
D:/bin/Sketchup7/Plugins/su2radlib/webdialog.rb:73:in `call'

Any suggestions as to how to avoid this problem of fix it ?

Thanks.

**Comment by gwgill** [comment]
Updates to latest githup code.
Failed to run because of line
   SKETCHUP_CONSOLE.show()
in su2rad_loader.rb. Commented out this line and it ran, but "reference to deleted Layer" problem remains:

[E] ERROR: no layer.name (reference to deleted Layer)
[E] reference to deleted Layer
D:/bin/Sketchup7/Plugins/su2radlib/radiancepolygon.rb:192:in 'name'
D:/bin/Sketchup7/Plugins/su2radlib/radiancepolygon.rb:192:in 'getLayerName'
D:/bin/Sketchup7/Plugins/su2radlib/radiancepolygon.rb:178:in 'getEffectiveLayerName'
D:/bin/Sketchup7/Plugins/su2radlib/radiancepolygon.rb:220:in 'getPolygonText'
D:/bin/Sketchup7/Plugins/su2radlib/radiancepolygon.rb:156:in 'getText'
D:/bin/Sketchup7/Plugins/su2radlib/exportbase.rb:156:in 'exportByGroup'
D:/bin/Sketchup7/Plugins/su2radlib/exportbase.rb:150:in 'each_index'
D:/bin/Sketchup7/Plugins/su2radlib/exportbase.rb:150:in 'exportByGroup'
D:/bin/Sketchup7/Plugins/su2radlib/exportscene.rb:170:in 'export'
D:/bin/Sketchup7/Plugins/su2radlib/exportscene.rb:136:in 'startExportWeb'
D:/bin/Sketchup7/Plugins/su2radlib/webdialog.rb:168:in 'startExport'
D:/bin/Sketchup7/Plugins/su2radlib/webdialog.rb:82:in 'show'
D:/bin/Sketchup7/Plugins/su2radlib/webdialog.rb:81:in 'call'

Commented out duplicate "layername = remove_spaces(layer.name)" outside "begin .. rescue .. end" on line 191
of radiancepolygon.rb and now it runs.

**Comment by gwgill** [comment]
Correct fix is to change line 166 of radiancepolygon.rb in function getEffectiveLayer() from
    if layer_s != nil
to
    if layer_s != nil && layer_s.valid?

**Comment by tbleicher** [comment]
Thanks, @gwgill. 

I added your fix to the code.
